{{ if eq .Values.installScope "cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ack-cloudfront-controller
  labels:
  {{- range $key, $value := .Values.role.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- include "controller-role-rules" . -}}
{{ else if .Values.watchNamespace }}
{{ $rules := include "controller-role-rules" . }}
{{ $namespaces := split "," .Values.watchNamespace }}
{{ range $namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ack-cloudfront-controller
  namespace: {{ . }}
  labels:
  {{- range $key, $value := .Values.role.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- $rules }}
{{ end }}
{{ end }}