---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-cloudfront-reader
  namespace: default
rules:
- apiGroups:
  - cloudfront.services.k8s.aws
  resources:
  - cachepolicies
  - distributions
  - functions
  - originrequestpolicies
  verbs:
  - get
  - list
  - watch
