apiVersion: v1
name: cloudfront-chart
description: A Helm chart for the ACK service controller for Amazon CloudFront (CloudFront)
version: 1.0.8
appVersion: 1.0.8
home: https://github.com/aws-controllers-k8s/cloudfront-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/cloudfront-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: CloudFront Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/cloudfront-maintainer
keywords:
  - aws
  - kubernetes
  - cloudfront
